<?php

return array(
	'now_here_common' => '当前位置',
	'operate_common' => '操作',
	'edit_common' => '修改',
	'add_common' => '添加',
	'update_common' => '更新',
	'del_common' => '删除',
	'delete' => '删除',
	'sort_common' => '排序',
	'save_common' => '保存',
	'reset_common' => '重置',
	'select_all_common' => '全选',
	'un_select_all_common' => '反选',
	'yes_common' => '是',
	'no_common' => '否',
	'batch_del_common' => '批量删除',
	'confirm_del_common' => '您确定要删除吗?',
	'download'=>'下载',
	
	'radio_common' => '单选框',
	'checkbox_common' => '复选框',
	'select_common' => '下拉框',
	'input_common' => '输入框',
	'op_title' => '操作',
	'op_check' => '审核',
	
	'no_permission' => '你没有操作该内容的权限!',
	'operation_success_common' => '操作成功!',
	'op_success' => '操作成功!',
	'operation_failed_common' => '操作失败!',
	'op_failed' => '操作失败!',
	'no_record_common' => '请选择要操作的记录',
	'empty_record_common' => '要操作的记录不存在，请确认',
	'no_field_common' => '请在参数指定要修改的域',
	'modify_success_common' => '修改成功!',
	'modify_failed_common' => '修改失败',
	
	// 公共
	'common_id' => 'ID',
	'common_parent_id' => '上级ID',
	'common_sort_num' => '排序',
	'common_is_show' => '是否显示',
	'common_status' => '状态',
	'common_subject' => '标题',
	'common_intro' => '简介',
	'common_caption' => '说明',
	'common_message' => '正文',
	'common_add_time' => '添加时间',
	'common_add_user' => '添加用户',
	'common_edit_time' => '修改时间',
	'common_edit_user' => '修改用户',
	'common_validity' => '有效期',
	'common_start_time' => '开始时间',
	'common_end_time' => '结束时间',
	'common_permanent' => '留空，则永久有效',
	'common_author' => '作者',
	'common_source' => '来源',
	'common_abstract' => '摘要',
	'common_keywords' => 'SEO关键字',
	'common_description' => 'SEO描述',
	'common_jump_url' => '跳转URL',
	'common_tag' => '标签',
	'common_thumb' => '缩略图',
	'common_catalog_tpl' => '栏目模板',
	'common_content_tpl' => '内容模板',
	'common_detail' => '详情',
	'common_upload_attach' => '上传附件',
	'common_upload_no_ext' => '不允许上传该类型的文件',
	'common_sort_desc' => '数字越大越靠前',
	'common_is_need' => '是否必填',
	
	'common_position' => '当前位置',
	'common_operate' => '操作',
	'common_edit' => '修改',
	'common_del' => '删除',
	'common_save' => '保存',
	'common_opt_del' => '批量删除',
	'common_select' => '选择',
	'common_module_setting' => '模块设置',
	'common_batch_handle' => '批量处理',
	'common_batch_confirm' => '您确定要进行此操作吗？',
	'common_no_optype' => '请选择要进行的操作',
	'common_batch_op_error' => '操作出错中断，可能有些信息没有更新',
	'common_batch_verify' => '批量审核',
	'common_confirm_verify' => '您确定要审核吗？',
	'common_move' => '移动',
	'common_read' => '已读',
	'common_keyword' => '关键字',
	
	'system_setting' => '系统管理',
	
	// system/config
	'base_tab_config' => '基础设置',
	'email_tab_config' => '邮件设置',
	'basic_tab_config' => '基础设置',
	'site_name_config' => '网站名称',
	'beian_config' => '网站备案',
	'copyright_config' => '网站版权',
	'wx_account_config' => '微信帐号',
	'admin_email_config' => '官方邮箱',
	'sina_weibo_config' => '新浪微博',
	'qq_weibo_config' => '腾讯微博',	
		
	'email_service_type_config' => '邮件服务',
	'email_smtp_config' => 'SMTP',
	'email_server_port_config' => '邮件服务器端口',
	'email_send_email_config' => '邮件发送账号',
	'email_send_email_password_config' => '账号密码',
	'email_reply_email_config' => '邮件回复账号',
	'email_ssl_config' => '加密连接(SSL)',
		
	//member/role
	'permission_setting'=>'权限设置',
		
	'login_failure'=>'登陆失败',
	'login_success'=>'登陆成功',
	'logout_success'=>'退出成功',
		
	'money_tab_config'=>'竞猜规则',
	'integral_invite_config'=>'邀请用户注册赠送积分',
	'integral_share_config'=>'竞猜分享积分奖励',
	'recharge_inviter_reward_config'=>'用户充值奖励金币比例(如0.1)',
	'pay_tab_config'=>'支付设置',
	'alipay_parter_id_config'=>'支付宝合作商ID',
	'alipay_parter_key_config'=>'支付宝合作商密钥',
	'alipay_parter_account_config'=>'支付宝合作商账号',
		
	'placard_tab_config'=>'公告设置',
	'placard_config'=>'公告',
	'guess_tax_config'=>'竞猜税收比例(如0.1)',
	'guess_add_check_config'=>'竞猜审核',
	'guess_custom_add_check_config'=>'自定义竞猜审核',
	'invite_open_config'=>'是否开启邀请码',
		
	'oauth_tab_config'=>'第三方登陆',
	'oauth_weibo_app_key_config'=>'新浪微博APP KEY',
	'oauth_weibo_app_sercet_config'=>'新浪微博APP SERCET',
	'oauth_qq_app_key_config'=>'腾讯APP KEY',
	'oauth_qq_app_sercet_config'=>'腾讯APP SERCET',
		
	'integral_register_config'=>'用户注册初始积分',
	'integral_user_info_config'=>'完善资料个人资料赠送积分',
		
	'ad_tab_config'=>'广告设置',
	'ad_config'=>'广告代码',
);
